linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

run:
  timeout: 10m
