version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - bodyclose
          - errcheck
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

formatters:
  enable:
    - gofmt
