package cli_test

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"testing"
	"time"

	"encoding/pem"

	"github.com/m-mizutani/gt"
	"github.com/secmon-lab/tamamo/pkg/service/tlscert"
)

func testHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
}

func TestServeHTTPConnection(t *testing.T) {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	gt.NoError(t, err)
	defer func() { _ = listener.Close() }()

	server := &http.Server{
		Handler:           testHandler(),
		ReadHeaderTimeout: 5 * time.Second,
	}
	defer func() { _ = server.Close() }()
	go func() { _ = server.Serve(listener) }()

	resp, err := http.Get("http://" + listener.Addr().String())
	gt.NoError(t, err)
	defer func() { _ = resp.Body.Close() }()
	gt.Value(t, resp.StatusCode).Equal(http.StatusOK)
}

func TestServeTLSAutoGenerated(t *testing.T) {
	// Generate self-signed cert (same as serve.go does with --tls)
	cert, err := tlscert.Generate()
	gt.NoError(t, err)

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	gt.NoError(t, err)
	defer func() { _ = listener.Close() }()

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{*cert},
		MinVersion:   tls.VersionTLS12,
	}
	tlsListener := tls.NewListener(listener, tlsConfig)

	server := &http.Server{
		Handler:           testHandler(),
		ReadHeaderTimeout: 5 * time.Second,
	}
	defer func() { _ = server.Close() }()
	go func() { _ = server.Serve(tlsListener) }()

	// Trust the generated CA
	caCert, err := x509.ParseCertificate(cert.Certificate[1])
	gt.NoError(t, err)
	caPool := x509.NewCertPool()
	caPool.AddCert(caCert)

	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				RootCAs:    caPool,
				MinVersion: tls.VersionTLS12,
			},
		},
	}

	resp, err := client.Get("https://" + listener.Addr().String())
	gt.NoError(t, err)
	defer func() { _ = resp.Body.Close() }()
	gt.Value(t, resp.StatusCode).Equal(http.StatusOK)
}

func TestServeTLSWithProvidedCert(t *testing.T) {
	// Generate cert files to disk (simulates --tls-cert / --tls-key)
	certFile, keyFile, caCertDER := generateCertFiles(t)

	// Load via tls.LoadX509KeyPair (same as serve.go does)
	loaded, err := tls.LoadX509KeyPair(certFile, keyFile)
	gt.NoError(t, err)

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	gt.NoError(t, err)
	defer func() { _ = listener.Close() }()

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{loaded},
		MinVersion:   tls.VersionTLS12,
	}
	tlsListener := tls.NewListener(listener, tlsConfig)

	server := &http.Server{
		Handler:           testHandler(),
		ReadHeaderTimeout: 5 * time.Second,
	}
	defer func() { _ = server.Close() }()
	go func() { _ = server.Serve(tlsListener) }()

	// Trust the CA
	caCert, err := x509.ParseCertificate(caCertDER)
	gt.NoError(t, err)
	caPool := x509.NewCertPool()
	caPool.AddCert(caCert)

	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				RootCAs:    caPool,
				MinVersion: tls.VersionTLS12,
			},
		},
	}

	resp, err := client.Get("https://" + listener.Addr().String())
	gt.NoError(t, err)
	defer func() { _ = resp.Body.Close() }()
	gt.Value(t, resp.StatusCode).Equal(http.StatusOK)
}

// generateCertFiles creates temporary cert and key PEM files for testing.
// Returns paths to the cert file, key file, and the raw CA certificate DER bytes.
func generateCertFiles(t *testing.T) (certPath, keyPath string, caCertDER []byte) {
	t.Helper()

	tmpDir := t.TempDir()

	// Generate CA
	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	gt.NoError(t, err)

	caTemplate := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject: pkix.Name{
			Organization: []string{"Test CA"},
		},
		NotBefore:             time.Now().Add(-1 * time.Hour),
		NotAfter:              time.Now().Add(24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	caCertBytes, err := x509.CreateCertificate(rand.Reader, caTemplate, caTemplate, &caKey.PublicKey, caKey)
	gt.NoError(t, err)

	caCert, err := x509.ParseCertificate(caCertBytes)
	gt.NoError(t, err)

	// Generate server cert signed by CA
	serverKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	gt.NoError(t, err)

	serverTemplate := &x509.Certificate{
		SerialNumber: big.NewInt(2),
		Subject: pkix.Name{
			CommonName: "localhost",
		},
		NotBefore:   time.Now().Add(-1 * time.Hour),
		NotAfter:    time.Now().Add(24 * time.Hour),
		KeyUsage:    x509.KeyUsageDigitalSignature,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:    []string{"localhost"},
		IPAddresses: []net.IP{net.IPv4(127, 0, 0, 1)},
	}

	serverCertBytes, err := x509.CreateCertificate(rand.Reader, serverTemplate, caCert, &serverKey.PublicKey, caKey)
	gt.NoError(t, err)

	// Write cert PEM
	certPath = filepath.Join(tmpDir, "server.crt")
	certOut, err := os.Create(certPath)
	gt.NoError(t, err)
	gt.NoError(t, pem.Encode(certOut, &pem.Block{Type: "CERTIFICATE", Bytes: serverCertBytes}))
	gt.NoError(t, certOut.Close())

	// Write key PEM
	keyPath = filepath.Join(tmpDir, "server.key")
	keyOut, err := os.Create(keyPath)
	gt.NoError(t, err)
	keyDER, err := x509.MarshalECPrivateKey(serverKey)
	gt.NoError(t, err)
	gt.NoError(t, pem.Encode(keyOut, &pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}))
	gt.NoError(t, keyOut.Close())

	return certPath, keyPath, caCertBytes
}
