package tlscert

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"net"
	"time"

	"github.com/m-mizutani/goerr/v2"
	"github.com/secmon-lab/tamamo/pkg/utils/errutil"
)

// Generate creates a self-signed CA and server certificate pair in memory.
// The certificates use OpenSSL-default-like subject attributes to appear
// as if generated by a lazy administrator using default openssl.cnf settings.
// NotBefore is randomly backdated 3–12 months to avoid looking freshly created.
func Generate() (*tls.Certificate, error) {
	notBefore, err := randomNotBefore()
	if err != nil {
		return nil, goerr.Wrap(err, "failed to generate random NotBefore",
			goerr.T(errutil.TagInternal),
		)
	}
	notAfter := notBefore.Add(2 * 365 * 24 * time.Hour)

	subject := opensslDefaultSubject()

	// Generate CA key pair
	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to generate CA key",
			goerr.T(errutil.TagInternal),
		)
	}

	caSerial, err := randomSerial()
	if err != nil {
		return nil, err
	}

	caTemplate := &x509.Certificate{
		SerialNumber: caSerial,
		Subject: pkix.Name{
			Country:            subject.Country,
			Province:           subject.Province,
			Organization:       subject.Organization,
			OrganizationalUnit: []string{},
		},
		NotBefore:             notBefore,
		NotAfter:              notAfter,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	caCertDER, err := x509.CreateCertificate(rand.Reader, caTemplate, caTemplate, &caKey.PublicKey, caKey)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create CA certificate",
			goerr.T(errutil.TagInternal),
		)
	}

	caCert, err := x509.ParseCertificate(caCertDER)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to parse CA certificate",
			goerr.T(errutil.TagInternal),
		)
	}

	// Generate server key pair
	serverKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to generate server key",
			goerr.T(errutil.TagInternal),
		)
	}

	serverSerial, err := randomSerial()
	if err != nil {
		return nil, err
	}

	serverTemplate := &x509.Certificate{
		SerialNumber: serverSerial,
		Subject: pkix.Name{
			Country:      subject.Country,
			Province:     subject.Province,
			Organization: subject.Organization,
			CommonName:   "localhost",
		},
		NotBefore:             notBefore,
		NotAfter:              notAfter,
		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		DNSNames:              []string{"localhost"},
		IPAddresses:           []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback},
	}

	serverCertDER, err := x509.CreateCertificate(rand.Reader, serverTemplate, caCert, &serverKey.PublicKey, caKey)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to create server certificate",
			goerr.T(errutil.TagInternal),
		)
	}

	cert := &tls.Certificate{
		Certificate: [][]byte{serverCertDER, caCertDER},
		PrivateKey:  serverKey,
	}

	return cert, nil
}

// opensslDefaultSubject returns a pkix.Name with OpenSSL default config values.
// These are the defaults from openssl.cnf that appear when a user generates
// a certificate without customizing the subject fields.
func opensslDefaultSubject() pkix.Name {
	return pkix.Name{
		Country:      []string{"AU"},
		Province:     []string{"Some-State"},
		Organization: []string{"Internet Widgits Pty Ltd"},
	}
}

// randomNotBefore returns a time randomly backdated between 3 and 12 months
// from now, so the certificate does not appear freshly generated.
func randomNotBefore() (time.Time, error) {
	const (
		minDays = 90  // 3 months
		maxDays = 365 // 12 months
	)
	rangeDays := maxDays - minDays
	n, err := rand.Int(rand.Reader, big.NewInt(int64(rangeDays)))
	if err != nil {
		return time.Time{}, goerr.Wrap(err, "failed to generate random offset",
			goerr.T(errutil.TagInternal),
		)
	}
	daysBack := minDays + int(n.Int64())
	return time.Now().AddDate(0, 0, -daysBack), nil
}

// randomSerial generates a random certificate serial number.
func randomSerial() (*big.Int, error) {
	serialLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialLimit)
	if err != nil {
		return nil, goerr.Wrap(err, "failed to generate serial number",
			goerr.T(errutil.TagInternal),
		)
	}
	return serial, nil
}
